name: Add Issue to Project 21

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/stjude-dnb-binfcore/projects/21
          github-token: ${{ secrets.PROJECT_TOKEN }}